name: GitHub-3D-Profile
description: Generate animated 3D isometric contribution calendar as SVG
author: xarthurx

runs:
  using: 'node24'
  main: 'dist/index.js'

branding:
  icon: 'box'
  color: 'green'
